title: Fyne Apps
email: info@fyne.io
url: "https://apps.fyne.io"

remote_theme: gdgmanagua/jekyll-mdl

header_type: default
post_type: highlight
updated_days: 180

disqus: true
disqus_shortname: 'fyne-apps'

more_vert:
  option1:
    name: Submit App
    link: https://developer.fyne.io/submit/

plugins:
  - jekyll-redirect-from

collections:
  apps:
    output: true
  categories:
    output: true
    permalink: /category/:name

defaults:
  - scope:
      path: ""
      type: "apps"
    values:
      layout: "app"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

